{
  "hash": "48bc423e1e730bb0ed452af9c8877270",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Collective defense strategies\"\neditor_options: \n  chunk_output_type: console\n---\n\n# Isolates selection\n\n## Rationale\n\nThe first phase of this study aimed to **select an entomopathogenic fungal isolate** to evaluate how a toxic substrate affects the collective immune defense of *Atta sexdens*.\n\nPathogenicity was evaluated on *A. sexdens* foragers exposed to five *Metarhizium robertsii* isolates—kindly provided by the *Laboratório de Interações Inseto-Microrganismos* at the *Universidade Federal de Viçosa*.\n\nTwenty-four hours prior to the bioassays, colonies were starved. Following starvation, **colonies were randomly assigned to two groups and exposed to one of two substrate regimes for seven days**: (i) 10.0 g of *Acalypha wilkesiana* leaves daily (control group), or (ii) 10.0 g of fresh *Tropaeolum majus* leaves daily, serving as a potential modulating agent of social defenses.\n\nAfter this period, **individual ants from these colonies were immersed for two seconds in a conidial suspension** at a concentration of 1x10⁶ conidia/mL, containing distilled water and 0.01% Tween 80. **Three control groups were evaluated**: (1) an aqueous solution of 0.01% Tween 80 (vehicle control), (2) distilled water (negative control), and (3) a 0.0001% isocycloseram solution (positive control). Each treatment consisted of four replicates (Petri dishes) with five foragers each. Ants were housed in Petri dishes lined with moistened filter paper and maintained in a BOD incubator at 27 ± 2 °C, 70 ± 10% relative humidity, and continuous darkness (0:24 h L:D). The ants were starved throughout the **4-day evaluation period**, and mortality was recorded daily. Dead individuals were immediately removed and transferred to individual moist chambers (microcentrifuge tubes containing cotton and autoclaved distilled water) to evaluate fungal sporulation (confirming mycosis).\n\n## Statistical analysis\n\nThe statistical analysis for the pathogenicity bioassay data was conducted in R using a multi-step framework. Survival curves were generated using the Kaplan–Meier estimator and compared across isolates and controls via the log-rank test to evaluate daily mortality rates. To quantify the hazard ratios (HR) of substrate type, fungal treatment, and their interaction (substrate:treatment), a mixed-effects Cox proportional hazards model (`coxme`) was fitted, specifying the Petri dish (replicate) as a random effect to account for pseudo-replication. Finally, the median lethal time (LT₅₀) for each treatment combination was estimated using dose-response modeling via the `drc` package.\n\n## Results\n\nInstalando e carregando os pacotes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl) #leitura do arquivo excel\nlibrary(dplyr) #manipulação dos dados\nlibrary(survival) #análise de sobrevivência\nlibrary(survminer) #gráficos de sobrevivência\n#install.packages(\"coxme\")\nlibrary(coxme) #modelo de cox com efeitos aleatórios\nlibrary(lme4) #modelos lineares generalizados mistos (glmm)\nlibrary(car) #ANOVA tipo III para glmm\n#install.packages(\"emmeans\")\nlibrary(emmeans) #comparações mútiplas post-hoc\n#install.packages()\nlibrary(drc) #curvas dose-resposta e cálculo de TL50\nlibrary(tidyverse)\n```\n:::\n\n\n### Foraging data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforaging_exp1 <- read_excel(\"foraging_bioassay_1.xlsx\")\n\nggplot(data = foraging_exp1, aes(x = real_consume, fill = substrate)) +\n    geom_histogram(alpha = .4) +\n    labs(title = \"Histogram\")\n```\n\n::: {.cell-output-display}\n![](coll_defe_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = foraging_exp1, aes(x = day, y = real_consume, fill = substrate)) +\n    geom_point(shape = 21, size = 4, color = \"black\")\n```\n\n::: {.cell-output-display}\n![](coll_defe_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = foraging_exp1, aes(x = day, y = real_consume,\n                            color = substrate, shape = substrate)) +\n    geom_point(size = 4, alpha = .7) +\n    geom_smooth(method = \"lm\", se = FALSE) +\n    scale_shape_manual(values = c(15, 17)) +\n    scale_color_manual(values = c(\"purple\", \"cyan4\")) +\n    theme_bw(base_size = 16) +\n    labs(x = \"day\", y = \"Substrate consume (g)\", \n         color = \"substrate\", shape = \"substrate\")\n```\n\n::: {.cell-output-display}\n![](coll_defe_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n:::\n\n\nPara analisar dados de consumo diário com medições repetidas nas mesmas colônias ao longo de 7 dias, a abordagem ideal é utilizar um Modelo Linear Misto (LMM) para isolar a autocorrelação temporal das colônias e contornar o baixo poder estatístico inicial do tamanho amostral (n = 3 colônias por substrato).Estatística Descritiva e ExploratóriaMétricas Diárias: Calcule média, erro-padrão da média (EPM), mediana e amplitude interquartil de real_consume agrupados por substrate e day.Objetivo: Mapear a trajetória central do consumo ao longo do tempo e verificar a variabilidade inter-colonial de cada grupo, além de identificar eventuais outliers.Análise Inferencial: Modelo Linear Misto (LMM)Por que usar: Cada colônia foi medida 7 vezes consecutivas, violando a premissa de independência de uma ANOVA tradicional. O LMM insere colony como efeito aleatório $(1 \\vert{} \\text{colony})$ para controlar a variação individual, enquanto substrate e day entram como efeitos fixos testando a interação $\\text{substrate} \\times \\text{day}$.Validação de Premissas: Avalie a normalidade dos resíduos do modelo via teste de Shapiro-Wilk. Caso os resíduos violem a normalidade, aplica-se transformação nos dados (ex: $\\log(y + 1)$) ou utiliza-se um Modelo Linear Generalizado Misto (GLMM) com distribuição Gama.Estratégia de Visualização CientíficaPara relatórios ou publicações, o gráfico ideal combina a tendência central do tratamento com a variação individual de cada unidade experimental (spaghetti plot sobreposto por médias):Linhas finas e transparentes ao fundo: Trajetória individual diária das 6 colônias (mostra a variação biológica real).Linhas espessas em destaque: Média diária de cada substrato ao longo dos 7 dias.Sombreamento (Ribbon): Representação gráfica do Erro-Padrão da Média ($\\pm \\text{SE}$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Pacotes Necessários --------------------------------------------------\nif (!require(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(tidyverse, lme4, lmerTest, car, emmeans)\n\n# 2. Dados Exemplo (Substitua pela leitura do seu CSV) -------------------\n# dados <- read.csv(\"seu_arquivo.csv\")\n\nset.seed(42)\ndados <- expand.grid(day = 1:7, colony = factor(1:6), substrate = c(\"Substrato_A\", \"Substrato_B\")) %>%\n  filter((substrate == \"Substrato_A\" & colony %in% 1:3) | \n         (substrate == \"Substrato_B\" & colony %in% 4:6)) %>%\n  mutate(real_consume = rnorm(n(), mean = ifelse(substrate == \"Substrato_A\", 10 + day*1.5, 8 + day*0.4), sd = 1.2))\n\n# 3. Estatística Descritiva -----------------------------------------------\ndescritiva <- dados %>%\n  group_by(substrate, day) %>%\n  summarise(\n    n = n(),\n    media = mean(real_consume, na.rm = TRUE),\n    se = sd(real_consume, na.rm = TRUE) / sqrt(n),\n    mediana = median(real_consume, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nprint(\"--- RESUMO DESCRITIVO ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- RESUMO DESCRITIVO ---\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(descritiva)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 6\n   substrate     day     n media    se mediana\n   <fct>       <int> <int> <dbl> <dbl>   <dbl>\n 1 Substrato_A     1     3 12.0  0.594   11.4 \n 2 Substrato_A     2     3 13.8  0.896   13.8 \n 3 Substrato_A     3     3 14.5  0.228   14.4 \n 4 Substrato_A     4     3 15.7  1.47    16.8 \n 5 Substrato_A     5     3 17.6  1.65    18.0 \n 6 Substrato_A     6     3 18.9  0.939   18.9 \n 7 Substrato_A     7     3 20.9  0.722   20.2 \n 8 Substrato_B     1     3  7.18 0.884    6.34\n 9 Substrato_B     2     3  8.16 0.222    8.03\n10 Substrato_B     3     3  9.53 0.724    9.75\n11 Substrato_B     4     3  9.67 1.54    10.4 \n12 Substrato_B     5     3 10.3  0.519   10.0 \n13 Substrato_B     6     3 10.1  0.283   10.1 \n14 Substrato_B     7     3 10.2  0.793   10.4 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 4. Modelo Linear Misto (LMM) -------------------------------------------\ndados$day_num <- as.numeric(dados$day)\n\n# Modelo testando efeito fixo do substrato, dia e interação, com efeito aleatório da colônia\nmodelo <- lmer(real_consume ~ substrate * day_num + (1 | colony), data = dados)\n\n# Teste de Normalidade dos Resíduos\nprint(\"--- NORMALIDADE DOS RESÍDUOS ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- NORMALIDADE DOS RESÍDUOS ---\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(shapiro.test(residuals(modelo)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(modelo)\nW = 0.98109, p-value = 0.7038\n```\n\n\n:::\n\n```{.r .cell-code}\n# Tabela ANOVA (Tipo III)\nprint(\"--- TABELA ANOVA (EFEITOS FIXOS) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- TABELA ANOVA (EFEITOS FIXOS) ---\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(Anova(modelo, type = \"III\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type III Wald chisquare tests)\n\nResponse: real_consume\n                     Chisq Df Pr(>Chisq)    \n(Intercept)       203.5219  1  < 2.2e-16 ***\nsubstrate           9.0434  1   0.002636 ** \nday_num            88.0044  1  < 2.2e-16 ***\nsubstrate:day_num  19.2067  1  1.173e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Médias Ajustadas e Comparações\nprint(\"--- MÉDIAS AJUSTADAS (EMMEANS) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- MÉDIAS AJUSTADAS (EMMEANS) ---\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(emmeans(modelo, ~ substrate | day_num))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nday_num = 4:\n substrate   emmean    SE df lower.CL upper.CL\n Substrato_A   16.2 0.411  4    15.06     17.3\n Substrato_B    9.3 0.411  4     8.16     10.4\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 5. Visualização Científica (ggplot2) -----------------------------------\ngrafico <- ggplot() +\n  # Trajetórias individuais de cada colônia\n  geom_line(data = dados, \n            aes(x = day, y = real_consume, group = colony, color = substrate),\n            alpha = 0.35, linetype = \"dashed\", linewidth = 0.7) +\n  # Intervalo de erro-padrão\n  geom_ribbon(data = descritiva, \n              aes(x = day, ymin = media - se, ymax = media + se, fill = substrate),\n              alpha = 0.2) +\n  # Linha média do substrato\n  geom_line(data = descritiva, \n            aes(x = day, y = media, color = substrate, group = substrate),\n            linewidth = 1.2) +\n  geom_point(data = descritiva, \n             aes(x = day, y = media, color = substrate), \n             size = 3) +\n  # Estética e Escalas\n  scale_x_continuous(breaks = 1:7) +\n  scale_color_brewer(palette = \"Set1\", name = \"Substrato\") +\n  scale_fill_brewer(palette = \"Set1\", name = \"Substrato\") +\n  labs(\n    x = \"Tempo de Exposição (Dias)\",\n    y = \"Consumo Real (g)\",\n    title = \"Dinâmica Diária de Forrageamento\",\n    subtitle = \"Média ± EPM (n = 3 colônias/substrato). Linhas pontilhadas indicam colônias individuais.\"\n  ) +\n  theme_classic(base_size = 12) +\n  theme(\n    legend.position = \"top\",\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(face = \"bold\")\n  )\n\nprint(grafico)\n```\n\n::: {.cell-output-display}\n![](coll_defe_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Survival curves (Kaplan-Meier)\n\nLendo e preparando os dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"isolates_selection_bioassay_1.xlsx\")\n\n#definindo as variáveis categóricas e criando um ID único por placa de Petri\ndados <- dados %>%\n  mutate(\n    substrate = as.factor(substrate),\n    treatment = as.factor(treatment),\n    inter     = as.factor(inter),\n    rep       = as.factor(rep),\n    id_placa  = as.factor(paste(inter, rep, sep = \"_\"))\n  )\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#criando o objeto de sobrevivência\nsurv_obj <- Surv(time = dados$dias, event = dados$mortality)\n\n#curvas de sobrevivência por tratamento de interação\nfit_km <- survfit(surv_obj ~ inter, data = dados)\n\n#teste de Log-Rank\nlogrank_test <- survdiff(surv_obj ~ inter, data = dados)\nprint(logrank_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = surv_obj ~ inter, data = dados)\n\n                 N Observed Expected (O-E)^2/E (O-E)^2/V\ninter=cont_cont 20       18     24.2   1.57863    3.5883\ninter=cont_i103 20       18     18.4   0.00998    0.0218\ninter=cont_i124 20       18     15.9   0.29100    0.5689\ninter=cont_i15  20       19     15.7   0.70299    1.3551\ninter=cont_i33  20       19     13.5   2.26444    4.2202\ninter=cont_i94  20       12     26.5   7.97012   18.3213\ninter=cont_isoc 20       20     18.4   0.13739    0.2964\ninter=cont_twee 20       15     23.7   3.17577    7.2090\ninter=trop_cont 20       17     20.3   0.52725    1.1229\ninter=trop_i103 20       14     26.2   5.69287   13.2331\ninter=trop_i124 20       20     13.7   2.91213    5.7328\ninter=trop_i15  20       19     12.1   3.88901    7.1066\ninter=trop_i33  20       20     14.9   1.78430    3.5608\ninter=trop_i94  20       20     14.5   2.05414    4.2385\ninter=trop_isoc 20       20     18.1   0.20646    0.4275\ninter=trop_twee 20       20     13.0   3.76980    7.4241\n\n Chisq= 76.6  on 15 degrees of freedom, p= 3e-10 \n```\n\n\n:::\n\n```{.r .cell-code}\n#plotando a curva de sobrevivência\nggsurvplot(\n  fit_km,\n  data = dados,\n  pval = TRUE,\n  risk.table = FALSE,\n  legend.title = \"Treatments\",\n  xlab = \"Days\",\n  ylab = \"Survival probability\",\n  ggtheme = theme_minimal()\n)\n```\n\n::: {.cell-output-display}\n![](coll_defe_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Mixed-effects Cox model (main effects + interaction)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_cox <- coxme(surv_obj ~ substrate * treatment + (1 | id_placa), data = dados)\nsummary(fit_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMixed effects coxme model\n Formula: surv_obj ~ substrate * treatment + (1 | id_placa) \n    Data: dados \n\n  events, n = 289, 320\n\nRandom effects:\n     group  variable        sd  variance\n1 id_placa Intercept 0.3530596 0.1246511\n                   Chisq   df         p   AIC    BIC\nIntegrated loglik  75.65 16.0 1.002e-09 43.65 -15.01\n Penalized loglik 125.66 31.6 3.632e-13 62.47 -53.37\n\nFixed effects:\n                               coef exp(coef) se(coef)     z      p\nsubstratetrop                0.1489    1.1606   0.4218  0.35 0.7240\ntreatmenti103                0.4156    1.5153   0.4183  0.99 0.3204\ntreatmenti124                0.5526    1.7378   0.4184  1.32 0.1866\ntreatmenti15                 0.7276    2.0700   0.4200  1.73 0.0832\ntreatmenti33                 0.9502    2.5863   0.4159  2.28 0.0223\ntreatmenti94                -0.7061    0.4936   0.4500 -1.57 0.1167\ntreatmentisoc                0.6991    2.0119   0.4128  1.69 0.0903\ntreatmenttwee               -0.1759    0.8387   0.4308 -0.41 0.6830\nsubstratetrop:treatmenti103 -1.0973    0.3338   0.6084 -1.80 0.0713\nsubstratetrop:treatmenti124  0.3197    1.3767   0.5980  0.53 0.5929\nsubstratetrop:treatmenti15   0.1732    1.1890   0.5930  0.29 0.7703\nsubstratetrop:treatmenti33  -0.1951    0.8228   0.5877 -0.33 0.7399\nsubstratetrop:treatmenti94   1.5473    4.6987   0.6177  2.51 0.0122\nsubstratetrop:treatmentisoc -0.2778    0.7575   0.5863 -0.47 0.6356\nsubstratetrop:treatmenttwee  1.2477    3.4822   0.6032  2.07 0.0386\n```\n\n\n:::\n:::\n\n\n### Median lethal time (LT₅₀) estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlt50_matrix <- quantile(fit_km, probs = 0.5)$quantile\n\nlt50_table <- data.frame(\n  Treatment_Group = gsub(\"inter=\", \"\", rownames(lt50_matrix)),\n  LT50_days = lt50_matrix[, 1],\n  row.names = NULL\n)\n\nprint(lt50_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Treatment_Group LT50_days\n1        cont_cont       3.0\n2        cont_i103       3.0\n3        cont_i124       2.0\n4         cont_i15       2.0\n5         cont_i33       2.0\n6         cont_i94       4.0\n7        cont_isoc       3.0\n8        cont_twee       3.0\n9        trop_cont       3.0\n10       trop_i103       4.0\n11       trop_i124       2.0\n12        trop_i15       2.0\n13        trop_i33       2.5\n14        trop_i94       3.0\n15       trop_isoc       3.0\n16       trop_twee       2.0\n```\n\n\n:::\n:::\n\n\nFungal pathogenicity and substrate interaction significantly affected Atta sexdens forager survival over time (Log-rank χ2 = 76.6, df = 15, p \\< 0.001). The mixed-effects Cox proportional hazards model revealed a significant interaction between substrate type and fungal isolate on mortality hazard (p = 0.0122). Specifically, exposure to isolate i94 on Tropaeolum majus substrate increased mortality risk 4.7-fold (HR = 4.70, z = 2.51, p = 0.0122) relative to control conditions. On the control substrate, isolate i33 displayed the highest independent toxicity (HR = 2.58, z = 2.28, p = 0.0223). Overall mortality was high across treatments and approached saturation by day 5, supporting the Cox proportional hazards analysis as the primary approach for assessing differences in mortality risk among treatments.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}